### ISSUE TITLE
Support for cereal 0.5.x

### ISSUE THREAD

**Issue by felixonmars** [jmillikin/haskell-dbus#2]
`Data.Serialize.Builder` was removed in favor of `Data.ByteString.Builder` in cereal 0.5.0.0. It would be great if haskell-dbus could make the necessary changes to support the new implementation.

Related to https://github.com/fpco/stackage/issues/946

**Comment by jmillikin** [comment]
Done in commit c5c64083ae9830da35ee7ed749c31b8d405f0d86.

**Comment by felixonmars** [comment]
Thanks a lot!
