### ISSUE TITLE
Constructors of Array, Dictionary and Structure

### ISSUE THREAD

**Issue by ptitfred** [jmillikin/haskell-dbus#5]
I may have missed something but I don't think we can instanciate any Array, Dictionary or Structure currently.

Those datatypes are also used as parameters, for instance in the notification service (https://developer.gnome.org/notification-spec).

Could we consider expose the constructors or provide some smart constructors like we have readers (`arrayItems`, `structureItems` and `dictionaryItems`) ?

**Comment by jmillikin** [comment]
`Array`, `Dictionary`, and `Structure` are for advanced use cases where client code needs to parse containers that contain unknown data types.

You generally shouldn't need to create them. When calling a method that expects a container, use the `IsVariant` class and standard Haskell containers such as `Vector`, `Map` or tuples.

**Comment by ptitfred** [comment]
Indeed, my bad. Thank you!

**Comment by ptitfred** [comment]
For the curious ones maybe passing by later, what I got working:

``` haskell
{-# LANGUAGE OverloadedStrings #-}

module Main where

import           Control.Monad (void)
import           Data.Int (Int32)
import qualified Data.Map as M (Map, empty)
import qualified Data.Vector as V (Vector, empty)
import           Data.Word (Word32)
import           DBus
import           DBus.Client

main :: IO ()
main = sendNotification "hello world"

sendNotification :: String -> IO ()
sendNotification text = do
  client <- connectSession
  notify client "haskellCli" 0 "" text "" 3000

notify :: Client -> String -> Word32 -> String -> String -> String -> Int32 -> IO ()
notify client appName replacesId appIcon summary body expireTimeout = do
  void $ call_ client (methodCall "/org/freedesktop/Notifications" "org.freedesktop.Notifications" "Notify")
    { methodCallDestination = Just "org.freedesktop.Notifications"
    , methodCallBody = [ toVariant appName
                       , toVariant replacesId
                       , toVariant appIcon
                       , toVariant summary
                       , toVariant body
                       , toVariant (V.empty :: V.Vector String)
                       , toVariant (M.empty :: M.Map String Variant)
                       , toVariant expireTimeout
                       ]
    }
```

**Comment by ptitfred** [comment]
@jmillikin I can add this to the examples if you don't mind
